add prerequests
rcarriga/nvim-notify pull request #139
Opened 2022-10-09 02:19 UTC by yinwoods

add prerequests for better landing with nvim-notify

2022-10-09 10:26 UTC, rcarriga requested changes
Thanks for the PR! Just a couple of wording changes, then LGTM :+1:

2022-10-09 10:26 UTC, rcarriga commented on README.md
> +* If you are using iTerm2 on MacOS, make sure to use a font which supported glyphs (icons), font can be found [here](https://github.com/ryanoasis/nerd-fonts).
This applies to all terminals, so we can remove the note about iterm2 to avoid confusion :smile:

2022-10-09 10:26 UTC, rcarriga commented on README.md
> +* Enable NeoVim show different colors in your `.vimrc` file or `.config/nvim/init.vim` file:
The wording is a bit odd and also I'd prefer to recommend the lua way of setting since new users are more likely to use that. Let's just say:

24-bit colour is required, which can be enabled by adding this to your `init.lua`
```lua
vim.opt.termguicolor = true
```

2022-10-09 11:15 UTC, yinwoods commented on README.md
> +* Enable NeoVim show different colors in your `.vimrc` file or `.config/nvim/init.vim` file:
Sure, that makes sense.

2022-10-09 14:18 UTC, rcarriga commented on README.md
> +* If you are using iTerm2 on MacOS, make sure to use a font which supported glyphs (icons), font can be found [here](https://github.com/ryanoasis/nerd-fonts).
Ah sorry I just meant we don't need to mention iterm, mentioning nerd fonts is a good idea! 
```md
Make sure to use a font which supports glyphs (icons), fonts can be found [here](https://github.com/ryanoasis/nerd-fonts).
```

2022-10-10 02:03 UTC, yinwoods commented on README.md
> +* If you are using iTerm2 on MacOS, make sure to use a font which supported glyphs (icons), font can be found [here](https://github.com/ryanoasis/nerd-fonts).
My bad, misunderstanding.

2022-10-10 07:17 UTC, rcarriga commented
Thanks again :grin:

2022-10-10 07:17 UTC, merged