Fix :  "attempt to index a number value"
rcarriga/nvim-notify pull request #253
Opened 2024-02-09 15:44 UTC by ls-devs

Fix "attempt to index a number value" on latest neovim build.

2024-02-09 16:02 UTC, dsully commented
This fixes `nvim-notify` on nightly for me as well.

2024-02-11 19:58 UTC, GitMurf commented
what is best way to apply this until the repo maintainer merges the PR? is the only real option to manually go replaces the file in my local installation? Thanks!

2024-02-11 20:23 UTC, ls-devs commented
> what is best way to apply this until the repo maintainer merges the PR? is the only real option to manually go replaces the file in my local installation? Thanks!

You can just change `rcarriga/nvim-notify` by `ls-devs/nvim-notify` in your nvim config where you call the plugin I guess ?

2024-02-14 11:03 UTC, dpetka2001 commented
This PR is incomplete. It doesn't work for Neovim 0.9.5 (latest stable). If it gets merged like this, users who use 0.9.5 will have notifications broken. Notifications work fine with the current state of `lua/notify/stages/util.lua` file. I would suggest adding guards against the version of Neovim being used. Something like
```lua
if vim.fn.has("nvim-0.10") then
  local exists, cur_win_conf = util.get_win_config(win)
else
  local exists, cur_win_conf = pcall(vim.api.nvim_win_get_config, win)
end
```
The same should be done for the rest of the changes made in this PR.

Maybe there is a better way to do this, but I believe you get the idea.

2024-02-14 12:16 UTC, ls-devs commented
@dpetka2001 Thank you for pointing it out.
For now I'll commit with guards everywhere it's needed. If anyone have an idea of how to do it more clean let us know.

2024-02-14 12:35 UTC, ls-devs commented
@dpetka2001 Let me know if this commit fix your issue.
But, tbh, I don't know if this is the right way to do it. There must be a cleaner way to achieve this without using `if ... else` everywhere in the code.

2024-02-14 13:08 UTC, dpetka2001 commented
Did you test it? For me it doesn't solve the issue. I created a branch in my forked repo that appears to solve it for both nightly and stable. [Here](https://github.com/dpetka2001/nvim-notify/commit/d590b4d5b24039887ebb3fc9087306f73d0ad43e) you can see the commit with the differences. Please feel free to incorporate the changes.

2024-02-14 14:09 UTC, dpetka2001 commented
@xfzv You're using the master branch which is the initial state of the fork. Use the `fix/index_value` branch like so
```lua
  {
    "dpetka2001/nvim-notify",
    branch = "fix/index_value",
  },
```

2024-02-14 14:09 UTC, ls-devs commented
> Did you test it? For me it doesn't solve the issue. I created a branch in my forked repo that appears to solve it for both nightly and stable. [Here](https://github.com/dpetka2001/nvim-notify/commit/d590b4d5b24039887ebb3fc9087306f73d0ad43e) you can see the commit with the differences. Please feel free to incorporate the changes. In your last commit you appear to make changes in the `window_intervals` function as well, but I believe that's not needed. Only the `slot_after_previous` function needs changes.

I tested it. But was in a hurry so I might no use the right `nvim` version. I rectified with your changes. Please tell me if it works because its working for me.

2024-02-14 14:20 UTC, latipun7 commented
The last change works for me too 👍

2024-02-14 14:21 UTC, dpetka2001 commented
@ls-devs Yes the latest changes solve the problem for both nightly and stable from the testing that I did. I would like to suggest that other people test it both on nightly and stable if possible, so that we haven't overlooked any edge case.

2024-02-14 14:36 UTC, dpetka2001 commented
@xfzv Please continue to use the branch of @ls-devs which is also associated with this PR. I will delete mine, since there's no purpose existing any more. I only created it to solve the problem for Neovim 0.9.5 which the initial state of the PR didn't take into account.

2024-02-14 18:01 UTC, iwansyahp commented
in case there is someone who use LazyVim and encounter same issue, you can use proposed solution here by creating a file under `~/.config/nvim/lua/plugins`

`nvim-notify.lua`
```
return {
  {
    "ls-devs/nvim-notify",
    keys = {
      {
        "<leader>un",
        function()
          require("notify").dismiss({ silent = true, pending = true })
        end,
        desc = "Dismiss all Notifications",
      },
    },
    opts = {
      timeout = 3000,
      max_height = function()
        return math.floor(vim.o.lines * 0.75)
      end,
      max_width = function()
        return math.floor(vim.o.columns * 0.75)
      end,
      on_open = function(win)
        vim.api.nvim_win_set_config(win, { zindex = 100 })
      end,
    },
    init = function()
      -- when noice is not enabled, install notify on VeryLazy
      if not require("lazyvim.util").has("noice.nvim") then
        require("lazyvim.util").on_very_lazy(function()
          vim.notify = require("notify")
        end)
      end
    end,
  },
}
```

2024-02-14 18:20 UTC, dpetka2001 commented
@iwansyahp I believe you don't need all this. With just 
```lua
return {
  {
    "ls-devs/nvim-notify",
    branch = "fix/fix_index_value",
  },
}
```
You should be ok. The `opts` from the LazyVim part should still be merged with yours.

2024-02-14 21:37 UTC, dpetka2001 commented
@ls-devs I like @kawre's idea and seems more maintainable as well. It's up to you to make the final decision to incorporate it or not.

2024-02-14 21:39 UTC, dpetka2001 requested changes

2024-02-14 21:39 UTC, dpetka2001 commented on lua/notify/stages/util.lua
> +  end
```suggestion
local exists, cur_win_conf = pcall(vim.api.nvim_win_get_config, win)
```
I would also suggest to leave this as it was, since it doesn't affect the problem at hand.

2024-02-14 21:47 UTC, ls-devs commented on lua/notify/stages/util.lua
> +  end
Of course @kawre idea is good and I'll take time to implement it tomorrow.

> I would also suggest to leave this as it was, since it doesn't affect the problem at hand.

The only reason I did this is because there is already an util function that does the same thing, so I thought it was a good idea to reuse what already exists.

2024-02-14 21:49 UTC, mehalter commented
Would it also be safer to do 

```lua
local function get_slot(conf, _key)
  return vim.fn.has "nvim-0.10" == 1 and conf[_key] or conf[_key][false]
end
```

That way it protects against whenever 1.0 comes out and the minor version goes below 10 again. Not that that's happening any time soon, but just for down the line.

2024-02-14 21:51 UTC, ls-devs commented
@mehalter You are totally true, I didn't thought about this kind of issue. Will correct it tomorrow.
Thank you for pointing it out.

2024-02-14 22:03 UTC, dpetka2001 commented on lua/notify/stages/util.lua
> +  end
Yes, but the util function also uses a `pcall` to `vim.api.nvim_win_get_config` under the hood as well, so it's essentially the same thing. And both basically return the window handler at hand. Also there's no need to make a check here for the Neovim version. Only at the places where `key` is existent.

2024-02-14 22:21 UTC, rcarriga commented
Thanks for the PR! :smile: I think the simplest solution here would be just switch both calls to `nvim_win_get_config` with `util.get_win_config` and then remove all `[false]` indexes (as if on >= 0.10.0). Am I missing something?

2024-02-14 22:30 UTC, dpetka2001 approved these changes

2024-02-14 22:35 UTC, dpetka2001 commented
Sorry for the wrong alert. I was under the assumption that when I make a suggestion I have to press `approve` for the PR to not be blocked. Still getting comfortable with Github and programming. Please disregard the `approved` notification by me.

2024-02-14 22:43 UTC, ls-devs commented
> Thanks for the PR! 😄 I think the simplest solution here would be just switch both calls to `nvim_win_get_config` with `util.get_win_config` and then remove all `[false]` indexes (as if on >= 0.10.0). Am I missing something?

Yes that's was in my mind. I'll make the changes a fast as I can tomorrow so it can be reviewed and tested 👍🏼

2024-02-15 07:44 UTC, ls-devs commented
@dpetka2001 , @rcarriga 

So I created `get_safe_slot`  function to handle all the case we need to remove `[false]` or not.
I also replaced `nvim_win_get_config` with `util.get_win_config`.
Would you please test it and tell me if it works for you ?

2024-02-15 08:09 UTC, wookayin commented
I don't think we need such an utility --- needing to use such a field accessor on every single callsite would be unnecessarily complicated and error-prone. We can instead make the `win_conf` table (returned by `util.get_win_config`) always contain a number "float" for all the relevant fields, no matter which nvim version is used. In this way one can access the number always with `win_conf[key]`.

2024-02-15 08:26 UTC, ls-devs commented
@wookayin Your idea seems to be the better solution for this issue. 
Would you please provide an example of how you would implement this ? I think I don't have enough knowledge about neovim to implement this alone.

2024-02-15 08:28 UTC, dpetka2001 commented
@ls-devs Based on what @rcarriga said, `util.get_win_config` seems to inherently manage this thing, so I don't believe you need the extra `slot` thing you added. I created an example branch based on what @rcarriga proposed. Take a look [here](https://github.com/dpetka2001/nvim-notify/commit/41e8dafa8eb39bbd4348cba2189c55394c780bb6).

2024-02-15 08:31 UTC, ls-devs commented
> @ls-devs Based on what @rcarriga said, `util.get_win_config` seems to inherently manage this thing, so I don't believe you need the extra `slot` thing you added. I created an example branch based on what @rcarriga proposed. Take a look [here](https://github.com/dpetka2001/nvim-notify/commit/41e8dafa8eb39bbd4348cba2189c55394c780bb6). I tested it on both stable and nightly and it seems to work on my end.

Sorry, I misunderstood what he said ! I thought both was necessary.
I'll make a quickfix and push it.

2024-02-15 08:33 UTC, dpetka2001 commented
Please also test it on your end after your local changes, just to avoid something that I might have missed.

2024-02-15 08:38 UTC, ls-devs commented
@dpetka2001 Can confirm it's working on both nightly and stable.
Sorry for the useless PRs and my misunderstanding of what @rcarriga said.

2024-02-15 08:43 UTC, dpetka2001 commented
No worries, I had also suggested in a previous comment to use the default Neovim API call instead of `util.get_win_config`, because I hadn't looked carefully into what it does until rcarriga proposed it. Then I looked again and realised that all these version checks were unnecessary, since `util.get_win_config` already makes that transformation for us and returns the window handler just like it's being returned from the Neovim API call in nightly as well.

2024-02-15 08:57 UTC, iwansyahp commented
thanks @dpetka2001 for your answer here, I am new to https://github.com/rcarriga/nvim-notify/pull/253#issuecomment-1944364850

2024-02-15 12:15 UTC, rcarriga commented
Awesome thanks for all the help everyone :grin:

2024-02-15 12:16 UTC, merged